# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151020170533 on 2015-10-23 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalCartBack', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='CartList',
        ),
        migrations.RenameField(
            model_name='cartlist',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='storeID',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='inventoryID',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='storeID',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='listitem',
            old_name='listID',
            new_name='cartlist',
        ),
        migrations.RenameField(
            model_name='listitem',
            old_name='itemID',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='storeID',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='userID',
            new_name='user',
        ),
    ]
