# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151020170533 on 2015-10-23 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalCartBack', '0002_auto_20151023_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.CharField(default=b'Good Store', max_length=4096),
        ),
    ]
