# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151020170533 on 2015-10-23 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalCartBack', '0003_auto_20151023_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='picture',
            field=models.CharField(default=b'images/default_user_image', max_length=128, null=True),
        ),
    ]
